//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace selahattin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aboutMe
    {
        public int id { get; set; }
        public string text1 { get; set; }
        public string image1 { get; set; }
        public string text2 { get; set; }
        public string image2 { get; set; }
    }
}
