//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace selahattin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siteIdentity
    {
        public int id { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string comment { get; set; }
        public string instagram { get; set; }
        public string linkedin { get; set; }
        public string github { get; set; }
        public string stacoverflow { get; set; }
        public string codepen { get; set; }
    }
}
